In [12]:
import numpy as np
a = [[1,2],[3,4,5]]
print(a)

[[1, 2], [3, 4, 5]]


In [17]:
a = np.array([[1,2],[3,4]],dtype=np.int32)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[1 2]
 [3 4]]
2
(2, 2)
4
int32


In [26]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
a = np.arange(10,36,5)
print(a)

[10 15 20 25 30 35]


In [25]:
a = np.linspace(1,10,5,dtype=np.int32)
print(a)

[ 1  3  5  7 10]


In [39]:
a = np.array(range(6))
print(a)
b = a.reshape((3,2))
print(a)
print(b)
print(b.T)
print(a.T)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 2 4]
 [1 3 5]]
[0 1 2 3 4 5]


In [58]:
a = np.array([[1,2],[3,4]])
b = np.array([[9,10],[11,12]])
c = np.vstack((a,b))
print("this is the original c")
print(c)
print("this is the splitted c")
x,y=np.vsplit(c,2)
print(x)



this is the original c
[[ 1  2]
 [ 3  4]
 [ 9 10]
 [11 12]]
this is the splitted c
[[1 2]
 [3 4]]
